## Experiment general information:
## generate_samples(): RPI 
## extract_features(): VM
## classify(): VM
## handle_class_result(): RPI
[meta]
version = 3
name = "offloading-experiments"
repetition = 30
description = "TtC and energy consumption test for both functions on VM node"
experiment = 'both-funcs-on-vm'
duration = 60       ## Duration of each run (s)

## Otii API configuration
[otii]
software_version = "3.5.3"
hostname = "127.0.0.1"
port = 1905
license_user = "<license-username>"
license_psw = "<license-password>"
baudrate = 115200

[rpi]
edgeless_exec_dir = "/home/pi/Desktop/edgeless/target/debug"
workflow_path = "../../workflows/workflow_both_funcs_on_vm.json"
ttc_logs_path = "/home/pi/Desktop/ttc_logs_ex_time/both_funcs_on_vm"

[params]